name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - develop
      - feature/**
      - dependabot/**

jobs:
  pr-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup environment with node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
#      - name: Load npm cache
#        id: check-npm-cache
#        uses: actions/cache@v1
#        with:
#          path: ~\AppData\Roaming\npm-cache
#          key: ${{ runner.os }}-node-${{ hashFiles('**\package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
      - name: Install yarn
        run: npm install -g yarn
#      - name: Load yarn cache
#        id: check-yarn-cache
#        uses: actions/cache@v1
#        with:
#          path: ./node_modules
#          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-
      - name: Install dependencies
#        if: steps.check-yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run linting
        run: |
          yarn run lint:scripts
      - name: Run unit tests with coverage
        run: |
          yarn run test:unit:coverage --token=${{secrets.CODACY_PROJECT_API_TOKEN}}
#      - name: Run integration tests
#        run: |
#          yarn run test:integration
