name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - develop
      - feature/**
      - dependabot/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Check yarn cache
        id: yarn-cache
        run: |
          npm install -g install
          echo "::set-output name=dir::$(yarn cache dir)"
      - name: Load yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup environment with node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Run linting
        run: |
          yarn run lint:scripts
      - name: Run unit tests
        run: |
          yarn run test:unit:coverage
      - name: Run integration tests
        run: |
          yarn run test:integration
